title: Grav
default_lang: gr
author:
  name: Alberto Scandolara
  email: "alberto.scandolara92.work@gmail.com"
metadata:
  description: "Emmanouela Milaki's website, showcasing her expertise, services, and contact information."
